# Generated by Django 3.2.18 on 2023-04-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storemetting',
            old_name='participant',
            new_name='no_of_participants',
        ),
    ]
